name: TruffleHog Secret Scan

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  - name: TruffleHog Secret Scan
    uses: trufflesecurity/trufflehog-actions-scan@v3 
    with:
      scan-directory: '.'
      branch: ${{ github.ref }} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
